# This YAML file should serve is the central config for this web app

# Flask app parameters
debug: True

# This is the cutoff date for all stock price training data (ie. nothing after this can be used for training)
training_date_cutoff: 2020-05-01